import type {
  ToolCategory,
  ToolDefinition,
  ToolInputType,
  ToolOperation,
  ToolProcessingMode,
} from "@toolkit-pro/shared-types";

const defaultBenefits = [
  "Fast server-side processing",
  "Secure signed download links",
  "No software installation required",
];

const defaultFaq = (formats: string[]) => [
  {
    question: "Are my files stored permanently?",
    answer: "Processed files are stored temporarily and conversion records expire automatically.",
  },
  {
    question: "Which formats are supported?",
    answer: `This tool accepts ${formats.map((f) => f.toUpperCase()).join(", ")} files.`,
  },
];

function createTool(input: {
  slug: string;
  name: string;
  category: ToolCategory;
  operation: ToolOperation;
  description: string;
  inputFormats: string[];
  outputFormats: string[];
  acceptedFormats: string[];
  acceptedMimeTypes: string[];
  outputFormat: string | "same";
  seoTitle: string;
  seoDescription: string;
  inputType?: ToolInputType;
  processingMode?: ToolProcessingMode;
  maxFiles?: number;
  searchKeywords?: string[];
}): ToolDefinition {
  const inputType =
    input.inputType ??
    (input.category === "text" ? "text" : input.operation === "merge" ? "multi-file" : "file");
  const processingMode =
    input.processingMode ?? (input.category === "pdf" || input.category === "document" ? "async" : "sync");

  return {
    ...input,
    inputType,
    processingMode,
    benefits: defaultBenefits,
    useCases: ["Everyday file workflows", "Business document handling", "Web publishing"],
    faq: defaultFaq(input.acceptedFormats.length ? input.acceptedFormats : input.inputFormats),
    isActive: true,
  };
}

const imageMime = {
  jpg: ["image/jpeg"],
  jpeg: ["image/jpeg"],
  png: ["image/png"],
  webp: ["image/webp"],
  gif: ["image/gif"],
  avif: ["image/avif"],
  tiff: ["image/tiff"],
  bmp: ["image/bmp"],
} as const;

function imageConvert(
  slug: string,
  name: string,
  from: keyof typeof imageMime,
  to: string,
  description: string,
) {
  const fromFormats = from === "jpg" ? ["jpg", "jpeg"] : [from];
  return createTool({
    slug,
    name,
    category: "image",
    operation: "convert",
    description,
    inputFormats: [...fromFormats],
    outputFormats: [to],
    acceptedFormats: [...fromFormats],
    acceptedMimeTypes: [...imageMime[from]],
    outputFormat: to,
    seoTitle: `${name} Converter`,
    seoDescription: `${description} online with ToolKit Pro.`,
  });
}

const imageTools: ToolDefinition[] = [
  imageConvert("jpg-to-png", "JPG to PNG", "jpg", "png", "Convert JPEG images to PNG"),
  imageConvert("png-to-jpg", "PNG to JPG", "png", "jpg", "Convert PNG images to JPEG"),
  imageConvert("jpg-to-webp", "JPG to WebP", "jpg", "webp", "Convert JPEG images to WebP"),
  imageConvert("png-to-webp", "PNG to WebP", "png", "webp", "Convert PNG images to WebP"),
  imageConvert("webp-to-jpg", "WebP to JPG", "webp", "jpg", "Convert WebP images to JPEG"),
  imageConvert("webp-to-png", "WebP to PNG", "webp", "png", "Convert WebP images to PNG"),
  imageConvert("jpg-to-gif", "JPG to GIF", "jpg", "gif", "Convert JPEG images to GIF"),
  imageConvert("gif-to-jpg", "GIF to JPG", "gif", "jpg", "Convert GIF images to JPEG"),
  imageConvert("png-to-gif", "PNG to GIF", "png", "gif", "Convert PNG images to GIF"),
  imageConvert("gif-to-png", "GIF to PNG", "gif", "png", "Convert GIF images to PNG"),
  imageConvert("webp-to-avif", "WebP to AVIF", "webp", "avif", "Convert WebP images to AVIF"),
  imageConvert("avif-to-webp", "AVIF to WebP", "avif", "webp", "Convert AVIF images to WebP"),
  imageConvert("jpg-to-tiff", "JPG to TIFF", "jpg", "tiff", "Convert JPEG images to TIFF"),
  imageConvert("tiff-to-jpg", "TIFF to JPG", "tiff", "jpg", "Convert TIFF images to JPEG"),
  imageConvert("bmp-to-png", "BMP to PNG", "bmp", "png", "Convert BMP images to PNG"),
  imageConvert("png-to-avif", "PNG to AVIF", "png", "avif", "Convert PNG images to AVIF"),
  createTool({
    slug: "compress-jpg",
    name: "Compress JPG",
    category: "image",
    operation: "compress",
    description: "Reduce JPEG file size while preserving visual quality.",
    inputFormats: ["jpg", "jpeg"],
    outputFormats: ["jpg"],
    acceptedFormats: ["jpg", "jpeg"],
    acceptedMimeTypes: ["image/jpeg"],
    outputFormat: "same",
    seoTitle: "Compress JPG Online",
    seoDescription: "Compress JPG images online.",
  }),
  createTool({
    slug: "compress-png",
    name: "Compress PNG",
    category: "image",
    operation: "compress",
    description: "Optimize PNG files for faster delivery.",
    inputFormats: ["png"],
    outputFormats: ["png"],
    acceptedFormats: ["png"],
    acceptedMimeTypes: ["image/png"],
    outputFormat: "same",
    seoTitle: "Compress PNG Online",
    seoDescription: "Compress PNG images online.",
  }),
  createTool({
    slug: "compress-webp",
    name: "Compress WebP",
    category: "image",
    operation: "compress",
    description: "Further optimize WebP images for production use.",
    inputFormats: ["webp"],
    outputFormats: ["webp"],
    acceptedFormats: ["webp"],
    acceptedMimeTypes: ["image/webp"],
    outputFormat: "same",
    seoTitle: "Compress WebP Online",
    seoDescription: "Compress WebP images online.",
  }),
  createTool({
    slug: "compress-gif",
    name: "Compress GIF",
    category: "image",
    operation: "compress",
    description: "Optimize GIF animations and graphics.",
    inputFormats: ["gif"],
    outputFormats: ["gif"],
    acceptedFormats: ["gif"],
    acceptedMimeTypes: ["image/gif"],
    outputFormat: "same",
    seoTitle: "Compress GIF Online",
    seoDescription: "Compress GIF images online.",
  }),
  createTool({
    slug: "resize-image",
    name: "Resize Image",
    category: "image",
    operation: "resize",
    description: "Resize images to custom dimensions.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["jpg", "png", "webp"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "same",
    seoTitle: "Resize Image Online",
    seoDescription: "Resize JPG, PNG, and WebP images online.",
  }),
  createTool({
    slug: "crop-image",
    name: "Crop Image",
    category: "image",
    operation: "crop",
    description: "Crop images to exact dimensions.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["jpg", "png", "webp"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "same",
    seoTitle: "Crop Image Online",
    seoDescription: "Crop JPG, PNG, and WebP images online.",
  }),
  createTool({
    slug: "rotate-image",
    name: "Rotate Image",
    category: "image",
    operation: "rotate",
    description: "Rotate images by 90, 180, or 270 degrees.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["jpg", "png", "webp"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "same",
    seoTitle: "Rotate Image Online",
    seoDescription: "Rotate images online.",
  }),
  createTool({
    slug: "flip-image",
    name: "Flip Image",
    category: "image",
    operation: "transform",
    description: "Flip images horizontally or vertically.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["jpg", "png", "webp"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "same",
    seoTitle: "Flip Image Online",
    seoDescription: "Flip images online.",
  }),
  createTool({
    slug: "strip-metadata",
    name: "Strip Image Metadata",
    category: "image",
    operation: "transform",
    description: "Remove EXIF and other metadata from images.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["jpg", "png", "webp"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "same",
    seoTitle: "Strip Image Metadata",
    seoDescription: "Remove metadata from images online.",
  }),
];

const pdfTools: ToolDefinition[] = [
  createTool({
    slug: "merge-pdf",
    name: "Merge PDF",
    category: "pdf",
    operation: "merge",
    description: "Combine multiple PDF files into one document.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "pdf",
    inputType: "multi-file",
    maxFiles: 20,
    seoTitle: "Merge PDF Online",
    seoDescription: "Merge multiple PDF files into one.",
  }),
  createTool({
    slug: "split-pdf",
    name: "Split PDF",
    category: "pdf",
    operation: "split",
    description: "Split a PDF into separate pages or ranges.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf", "zip"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "zip",
    seoTitle: "Split PDF Online",
    seoDescription: "Split PDF files online.",
  }),
  createTool({
    slug: "compress-pdf",
    name: "Compress PDF",
    category: "pdf",
    operation: "compress",
    description: "Reduce PDF file size for sharing and upload.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "same",
    seoTitle: "Compress PDF Online",
    seoDescription: "Compress PDF files online.",
  }),
  createTool({
    slug: "rotate-pdf",
    name: "Rotate PDF",
    category: "pdf",
    operation: "rotate",
    description: "Rotate PDF pages to the correct orientation.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "same",
    seoTitle: "Rotate PDF Online",
    seoDescription: "Rotate PDF pages online.",
  }),
  createTool({
    slug: "delete-pages-pdf",
    name: "Delete PDF Pages",
    category: "pdf",
    operation: "extract",
    description: "Remove selected pages from a PDF.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "same",
    seoTitle: "Delete PDF Pages",
    seoDescription: "Delete pages from a PDF online.",
  }),
  createTool({
    slug: "extract-pages-pdf",
    name: "Extract PDF Pages",
    category: "pdf",
    operation: "extract",
    description: "Extract specific pages from a PDF.",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "pdf",
    seoTitle: "Extract PDF Pages",
    seoDescription: "Extract pages from a PDF online.",
  }),
  createTool({
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "pdf",
    operation: "convert",
    description: "Convert PDF pages to JPG images.",
    inputFormats: ["pdf"],
    outputFormats: ["jpg"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "jpg",
    seoTitle: "PDF to JPG Converter",
    seoDescription: "Convert PDF to JPG online.",
  }),
  createTool({
    slug: "pdf-to-png",
    name: "PDF to PNG",
    category: "pdf",
    operation: "convert",
    description: "Convert PDF pages to PNG images.",
    inputFormats: ["pdf"],
    outputFormats: ["png"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "png",
    seoTitle: "PDF to PNG Converter",
    seoDescription: "Convert PDF to PNG online.",
  }),
  createTool({
    slug: "images-to-pdf",
    name: "Images to PDF",
    category: "pdf",
    operation: "convert",
    description: "Combine images into a single PDF document.",
    inputFormats: ["jpg", "jpeg", "png", "webp"],
    outputFormats: ["pdf"],
    acceptedFormats: ["jpg", "jpeg", "png", "webp"],
    acceptedMimeTypes: ["image/jpeg", "image/png", "image/webp"],
    outputFormat: "pdf",
    inputType: "multi-file",
    maxFiles: 20,
    seoTitle: "Images to PDF",
    seoDescription: "Convert images to PDF online.",
  }),
  createTool({
    slug: "pdf-to-text",
    name: "PDF to Text",
    category: "pdf",
    operation: "extract",
    description: "Extract text content from PDF files.",
    inputFormats: ["pdf"],
    outputFormats: ["txt"],
    acceptedFormats: ["pdf"],
    acceptedMimeTypes: ["application/pdf"],
    outputFormat: "txt",
    seoTitle: "PDF to Text",
    seoDescription: "Extract text from PDF online.",
  }),
];

function documentTool(
  slug: string,
  name: string,
  inputFormats: string[],
  outputFormats: string[],
  mimeTypes: string[],
  description: string,
) {
  return createTool({
    slug,
    name,
    category: "document",
    operation: "convert",
    description,
    inputFormats,
    outputFormats,
    acceptedFormats: inputFormats,
    acceptedMimeTypes: mimeTypes,
    outputFormat: outputFormats[0] ?? "pdf",
    seoTitle: name,
    seoDescription: `${description} online.`,
  });
}

const documentTools: ToolDefinition[] = [
  documentTool(
    "docx-to-pdf",
    "DOCX to PDF",
    ["docx"],
    ["pdf"],
    ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    "Convert Word documents to PDF",
  ),
  documentTool(
    "pptx-to-pdf",
    "PPTX to PDF",
    ["pptx"],
    ["pdf"],
    ["application/vnd.openxmlformats-officedocument.presentationml.presentation"],
    "Convert PowerPoint presentations to PDF",
  ),
  documentTool(
    "xlsx-to-pdf",
    "XLSX to PDF",
    ["xlsx"],
    ["pdf"],
    ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    "Convert Excel spreadsheets to PDF",
  ),
  documentTool(
    "pdf-to-docx",
    "PDF to DOCX",
    ["pdf"],
    ["docx"],
    ["application/pdf"],
    "Convert PDF files to editable Word documents",
  ),
  documentTool(
    "xlsx-to-csv",
    "XLSX to CSV",
    ["xlsx"],
    ["csv"],
    ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    "Convert Excel spreadsheets to CSV",
  ),
  documentTool(
    "csv-to-xlsx",
    "CSV to XLSX",
    ["csv"],
    ["xlsx"],
    ["text/csv", "application/vnd.ms-excel"],
    "Convert CSV files to Excel spreadsheets",
  ),
  documentTool(
    "docx-to-text",
    "DOCX to Text",
    ["docx"],
    ["txt"],
    ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    "Extract plain text from Word documents",
  ),
  documentTool(
    "md-to-pdf",
    "Markdown to PDF",
    ["md", "markdown"],
    ["pdf"],
    ["text/markdown", "text/plain"],
    "Convert Markdown files to PDF",
  ),
  documentTool(
    "rtf-to-pdf",
    "RTF to PDF",
    ["rtf"],
    ["pdf"],
    ["application/rtf", "text/rtf"],
    "Convert RTF documents to PDF",
  ),
  documentTool(
    "odt-to-pdf",
    "ODT to PDF",
    ["odt"],
    ["pdf"],
    ["application/vnd.oasis.opendocument.text"],
    "Convert OpenDocument text files to PDF",
  ),
];

function textTool(slug: string, name: string, description: string, searchKeywords: string[] = []) {
  return createTool({
    slug,
    name,
    category: "text",
    operation: "transform",
    description,
    inputFormats: ["text"],
    outputFormats: ["text"],
    acceptedFormats: ["text"],
    acceptedMimeTypes: ["text/plain"],
    outputFormat: "same",
    inputType: "text",
    processingMode: "sync",
    seoTitle: name,
    seoDescription: `${description} online.`,
    searchKeywords,
  });
}

const textTools: ToolDefinition[] = [
  textTool("json-formatter", "JSON Formatter", "Format and prettify JSON", ["json", "format"]),
  textTool("json-minify", "JSON Minify", "Minify JSON by removing whitespace", ["json", "minify"]),
  textTool("json-to-csv", "JSON to CSV", "Convert JSON arrays to CSV", ["json", "csv"]),
  textTool("csv-to-json", "CSV to JSON", "Convert CSV data to JSON", ["csv", "json"]),
  textTool("base64-encode", "Base64 Encode", "Encode text to Base64", ["base64", "encode"]),
  textTool("base64-decode", "Base64 Decode", "Decode Base64 text", ["base64", "decode"]),
  textTool("url-encode", "URL Encode", "Percent-encode text for URLs", ["url", "encode"]),
  textTool("url-decode", "URL Decode", "Decode percent-encoded URL text", ["url", "decode"]),
  textTool("md5-hash", "MD5 Hash", "Generate MD5 hashes from text", ["hash", "md5"]),
  textTool("sha256-hash", "SHA-256 Hash", "Generate SHA-256 hashes from text", ["hash", "sha256"]),
  textTool("qr-code-generator", "QR Code Generator", "Generate QR codes from text or URLs", ["qr", "code"]),
  textTool("word-counter", "Word Counter", "Count words, characters, and lines", ["words", "count"]),
  textTool("case-converter", "Case Converter", "Convert text between letter cases", ["uppercase", "lowercase"]),
  textTool("markdown-to-html", "Markdown to HTML", "Convert Markdown to HTML", ["markdown", "html"]),
  textTool("html-to-text", "HTML to Text", "Strip HTML tags and extract plain text", ["html", "text"]),
];

export const allTools: ToolDefinition[] = [...imageTools, ...pdfTools, ...documentTools, ...textTools];
